### ISSUE TITLE
Early access dies when apid is down

### ISSUE THREAD

**Issue by gbrail** [apigee/microgateway-core#64]
Here's what I did:

1) Start apid and MGW
2) Send some API calls that include verifying the API key to show that the MGW works
3) Kill apid
4) Send the same API calls again
5) I get the stack trace below

Error long polling apid. Waiting 10 second then will retry... connect ECONNREFUSED 127.0.0.1:9010
error verify-api-key code=ECONNREFUSED, errno=ECONNREFUSED, syscall=connect, address=127.0.0.1, port=9010
error m=GET, u=/iloveapis, h=localhost:8000, r=::ffff:127.0.0.1:59505, s=200, name=Error, message=connect ECONNREFUSED 127.0.0.1:9010, code=ECONNREFUSED, stack=Error: connect ECONNREFUSED 127.0.0.1:9010
    at Object.exports._errnoException (util.js:1029:11)
    at exports._exceptionWithHostPort (util.js:1052:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
error verify-api-key message=connect ECONNREFUSED 127.0.0.1:9010, code=ECONNREFUSED, errno=ECONNREFUSED, syscall=connect, address=127.0.0.1, port=9010
/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/async/lib/async.js:43:36
    at /Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/async/lib/async.js:723:17
    at /Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/async/lib/async.js:167:37
    at fx (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/microgateway-core/lib/plugins-middleware.js:414:13)
    at Request._callback (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/microgateway-plugins/verify-api-key/index.js:44:13)
    at self.callback (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
Removing the socket file as part of cleanup
/Users/gregbrail/homebrew/lib/node_modules/edgemicro/cli/lib/reload-cluster.js:96
    var interval = respawnIntervalManager.getIntervalForNextSpawn(now);
                                          ^

TypeError: respawnIntervalManager.getIntervalForNextSpawn is not a function
    at replaceWorker (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/cli/lib/reload-cluster.js:96:43)
    at EventEmitter.replaceAndTerminateWorker (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/cli/lib/reload-cluster.js:120:5)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at emit (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/cli/lib/reload-cluster.js:56:15)
    at EventEmitter.emitWorkerDisconnect (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/cli/lib/reload-cluster.js:168:5)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:211:13)
    at Object.onceWrapper (events.js:293:19)
$

**Comment by mdobson** [comment]
I'll take a look.

**Comment by mdobson** [comment]
I've got a fix for this in https://github.com/apigee/microgateway-plugins/pull/27
