### ISSUE TITLE
Early Access won't start if no configurations are staged

### ISSUE THREAD

**Issue by gbrail** [apigee/microgateway-core#65]
I tried un-staging the bundle that was staged to the gateway while the MGW was running. The gateway crashed.

Upon restart, I get the output below.

I think that if nothing is staged, the gateway should remain up and running, awaiting something to be deployed.

edgemicro start -s ./systemConfig.yaml -a http://localhost:9010
current nodejs version is v7.7.1 current edgemicro version is 3.0.0-early-access
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/microgateway-config/lib/apid.js:52:31)
    at Request.self.callback (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:293:19)

**Comment by mdobson** [comment]
https://github.com/apigee/microgateway-config/pull/20
